# Docker Compose configuration
# Note: Compose can now delegate builds to Docker Buildx for better performance.
# See: https://docs.docker.com/compose/compose-file/build/

services:
  backend1:
    build: ./Backend
    environment:
      - SERVER_NAME=backend1
    ports:
      - "8001:8000"
    networks:
      - app-network

  backend2:
    build: ./Backend
    environment:
      - SERVER_NAME=backend2
    ports:
      - "8002:8000"
    networks:
      - app-network

  backend3:
    build: ./Backend
    environment:
      - SERVER_NAME=backend3
    ports:
      - "8003:8000"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

  frontend:
    build: ./Frontend
    environment:
      - BACKEND_URL=http://localhost:8000/
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge